- CHANGES.rst
- setup.py
- src/brasil/gov/temas/themes/amarelo/rules.xml
- src/brasil/gov/temas/themes/azul/rules.xml
- src/brasil/gov/temas/themes/branco/rules.xml
- src/brasil/gov/temas/themes/verde/rules.xml
- versions.cfg
Dessa forma, a viewlet de línguas pode ser adicionada via viewlet ou
customização na zmi.
> Nova regra permite div de línguas sem customização do tema.

- src/brasil/gov/temas/themes/amarelo/css/style.css
- src/brasil/gov/temas/themes/branco/css/style.css
> Corrigido css de linguas dos temas amarelo e branco.

- CHANGES.rst
- src/brasil/gov/temas/themes/amarelo/index.html
- src/brasil/gov/temas/themes/amarelo/rules.xml
- src/brasil/gov/temas/themes/azul/index.html
- src/brasil/gov/temas/themes/azul/rules.xml
- src/brasil/gov/temas/themes/branco/index.html
- src/brasil/gov/temas/themes/branco/rules.xml
- src/brasil/gov/temas/themes/verde/index.html
- src/brasil/gov/temas/themes/verde/rules.xml
Prepara pacote para esperar uma div de id "barra_brasil_js", que conterá a
chamada em javascript para a barra brasil na nova versão de brasil.gov.barra.
> Prepara tema para chamada da barra brasil.

- CHANGES.rst
- src/brasil/gov/temas/jbot/Products.TinyMCE.skins.tinymce.plugins.plonebrowser.css.plonebrowser.css
- src/brasil/gov/temas/jbot/Products.TinyMCE.skins.tinymce.plugins.table.css.cell.css
- src/brasil/gov/temas/jbot/Products.TinyMCE.skins.tinymce.plugins.table.css.merge_cells.css
- src/brasil/gov/temas/jbot/Products.TinyMCE.skins.tinymce.plugins.table.css.row.css
- src/brasil/gov/temas/jbot/Products.TinyMCE.skins.tinymce.plugins.table.css.table.css
Ainda não fiz testes no Windows.
> Corrige o tamanho das fontes dos popups do editor TinyMCE.

- webpack/app/brasilgovtemas.js
- webpack/app/index.html
- webpack/app/padrao/brasilgovtemas.scss
- webpack/app/scss/_basic.scss
- webpack/app/scss/_header.scss
Estilos básicos para o texto do NITF e textos
> Estilos para o texto do NITF

- webpack/app/index.html
- webpack/app/scss/_header.scss
Reorganiza o HTML do header para permitir melhor controle sobre os elementos
> Reorganização do HTML do topo

- webpack/app/scss/_grid.scss
- webpack/app/scss/_responsive.scss
Ajuste básico de responsividade para impedir falha nos testes
> Ajuste básico de responsividade

- CHANGES.rst
- webpack/app/scss/_header.scss
Ajustes de fontes e cores do topo do portal
> Revisão de estilos do topo

- CHANGES.rst
- webpack/app/rules.xml
> Ajusta exibição dos scripts do painel de controle

- CHANGES.rst
- webpack/app/rules.xml
> Fix license reference

- webpack/app/rules.xml
- webpack/app/scss/_header.scss
Estilos para a busca expandida por padrão na página inicial.
> Estilos para o funcionamento da busca expandida na pagina inicial

- CHANGES.rst
- webpack/app/brasilgovtemas.js
- webpack/app/index-minimalista.html
- webpack/app/index.html
- webpack/app/rules.xml
- webpack/app/scss/_header.scss
Estilos para a variação do topo do portal, quando utilizando a opção de busca expansivel
> Estilos para a variação do topo

- webpack/app/scss/_tiles.scss
Pequenos ajustes de estilos dos tiles
> Ajustes estilos tiles

- README.rst
Deixa apenas os dois temas existentes no readme, com preview atualizado.
> Adiciona preview dos temas ao readme

- CHANGES.rst
- webpack/app/index-minimalista.html
- webpack/app/index.html
- webpack/app/scss/_basic.scss
Deixa marcado os links quando acessados via teclado.
Deixa os links do skip links visíveis apenas quando acessados pelo teclado.
> Acessibilidade

- webpack/app/scss/_header.scss
> Propriedades da imagem de fundo da busca home 

- CHANGES.rst
- webpack/app/rules.xml
para permitir internacionalização
> Move link para voltar para o topo em um viewlet no brasil.gov.portal

- CHANGES.rst
- webpack/app/brasilgovtemas.js
- webpack/app/js/sociallike.js
- webpack/app/scss/_content.scss
- webpack/app/scss/_grid.scss
> Limita movimentação dos ícones de redes sociais para não invadir o

- webpack/app/scss/_grid.scss
Corrige erro de posicionamento do Destaque Topo causado pelas alterações de posicionamento do social like
> Corrige posicionamento do destaque topo

- CHANGES.rst
- webpack/app/scss/_tiles.scss
Estilos para deixar o resultado do tile de coleção lado a lado
> Estilos para o tile de colecao

- CHANGES.rst
- webpack/app/scss/_header.scss
Estilos para usar o video como fundo da area de busca no header expansivel
> Doodle video

- CHANGES.rst
- webpack/app/scss/_responsive.scss
Correções de erros do responsivo
> Corrige erros do responsivo

- CHANGES.rst
- webpack/app/scss/_content.scss
Corrige posicionamento que impedia o usuario de clicar no link de trocar a senha
> Troca senha

- CHANGES.rst
- webpack/app/rules.xml
Corrige o problema descrito em https://github.com/plonegovbr/brasil.gov.portal/issues/565
> Corrige o atributo data-base-url do body

- .travis.yml
- buildout.cfg
- src/brasil/gov/temas/tests/tests_funcionais.py
Corrige os erros de flake8 e altera o buildout para utilizar as versões da branch 1.x;
> Fix flake8

- CHANGES.rst
- src/brasil/gov/temas/themes/amarelo/rules.xml
- src/brasil/gov/temas/themes/azul/rules.xml
- src/brasil/gov/temas/themes/branco/rules.xml
- src/brasil/gov/temas/themes/verde/rules.xml
Exibe corretamente o valor do atributo data-base-url na tag Body. Corrige o erro na atribuição de permissões locais.
Baseado no pull request #249. HT @agnogueira.
Fix plonegovbr/brasil.gov.portal#565 na branch 1.x
> Exibe corretamente o valor do atributo data-base-url na tag Body.

- CHANGES.rst
- webpack/app/scss/_responsive.scss
Corrige o problema https://github.com/plonegovbr/brasil.gov.temas/issues/250
> Destaque topo no responsivo
